apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqldata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqldata
  template:
    metadata:
      labels:
        app: sqldata
    spec:
      containers:
      - name: sqldata
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_SA_PASSWORD
            value: {{ .Values.password }}
        ports:
        - containerPort: {{ .Values.ports.container }}
        resources: {}