apiVersion: v1
kind: Service
metadata:
  name: sqldata
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.ports.service }}
    targetPort: {{ .Values.ports.container }}
  selector:
    app: sqldata