apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketapi
  template:
    metadata:
      labels:
        app: basketapi
    spec:
      containers:
      - name: basketapi
        image: arteshop/basketapi
        imagePullPolicy: IfNotPresent
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_URLS
            value: http://0.0.0.0:80
          - name: EventBusConnection
            value: rabbitmq
          - name: AzureServiceBusEnabled
            value: "False"
          - name: ConnectionString
            value: redis
          - name: IdentityUrlExternal
            value: http://identity.webspa.my:8080
          - name: PATH_BASE
            value: "/basket-api"
          - name: GRPC_PORT
            value: "81"
          - name: identityUrl
            value: http://identity-api.default.svc.cluster.local
          - name: PORT
            value: "80"
        ports:
        - containerPort: 80
        - containerPort: 81