apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderssignalrhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderssignalrhub
  template:
    metadata:
      labels:
        app: orderssignalrhub
    spec:
      containers:
      - name: orderssignalrhub
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_URLS
            value: http://0.0.0.0:80
          - name: EventBusConnection
            value: {{ .Values.service.rabbitmq }}
          - name: AzureServiceBusEnabled
            value: "False"
          - name: identityUrl
            value: {{ .Values.service.identity }}
          - name: HostOrigin
            value:  http://{{ .Values.ingress.webspa }}
        ports:
        - containerPort: {{ .Values.ports.container }}