apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqldata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqldata
  template:
    metadata:
      labels:
        app: sqldata
    spec:
      containers:
      - name: sqldata
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_SA_PASSWORD
            value: Pass@word
        ports:
        - containerPort: 1433
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sqldata
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 5433
    targetPort: 1433
  selector:
    app: sqldata