apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingressmywebspa
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: {{ .Values.ingress.webspa }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.webspa }}
            port:
              number: 80
  - host: {{ .Values.ingress.identity }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.identityapi }}
            port:
              number: 80
  - host: {{ .Values.ingress.webapigw }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.webshopapigw }}
            port:
              number: 80
  - host: {{ .Values.ingress.signalrhub }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.signalrhub }}
            port:
              number: 80
  # ingressClassName: nginx
  