#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["NuGet.config", "."]
COPY ["Services/Coupon/Coupon.API/Coupon.API.csproj", "Services/Coupon/Coupon.API/"]
COPY ["Services/Coupon/Coupon.Infrastructure/Coupon.Infrastructure.csproj", "Services/Coupon/Coupon.Infrastructure/"]
COPY ["BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.csproj", "BuildingBlocks/EventBus/EventBusRabbitMQ/"]
COPY ["BuildingBlocks/EventBus/EventBus/EventBus.csproj", "BuildingBlocks/EventBus/EventBus/"]
COPY ["BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.csproj", "BuildingBlocks/EventBus/EventBusServiceBus/"]
COPY ["BuildingBlocks/EventBus/IntegrationEventLogEF/IntegrationEventLogEF.csproj", "BuildingBlocks/EventBus/IntegrationEventLogEF/"]
COPY ["Services/Coupon/Coupon.Domain/Coupon.Domain.csproj", "Services/Coupon/Coupon.Domain/"]
RUN dotnet restore "Services/Coupon/Coupon.API/Coupon.API.csproj"
COPY . .
WORKDIR "/src/Services/Coupon/Coupon.API"
RUN dotnet build "Coupon.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Coupon.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Coupon.API.dll"]