apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordersapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordersapi
  template:
    metadata:
      labels:
        app: ordersapi
    spec:
      containers:
      - name: ordersapi
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_URLS
            value: http://0.0.0.0:80
          - name: identityUrl
            value: {{ .Values.service.identity }}
          - name: IdentityUrlExternal
            value: http://{{ .Values.ingress.identity }}
          - name: ConnectionString
            value: Server={{ .Values.service.sqldata }},5433;Database=Microsoft.eShopOnContainers.Services.OrderingDb;User Id=sa;Password=Pass@word
          - name: EventBusConnection
            value: {{.Values.serivice.rabbitmq}}
          - name: UseCustomizationData
            value: "False"
          - name: AzureServiceBusEnabled
            value: "False"
          - name: CheckUpdateTime
            value: "30000"
          - name: PATH_BASE
            value: {{ .Values.path_base }}
          - name: UseLoadTest
            value: "False"
          - name: Serilog__MinimumLevel__Override__Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ
            value: Verbose
          - name: Serilog__MinimumLevel__Override__ordering-api
            value: Verbose
          - name: GRPC_PORT
            value: {{ .Values.ports.grpc | quote }}
          - name: PORT
            value: {{ .Values.ports.container | quote }}
        ports:
        - containerPort: {{ .Values.ports.container }}
        - containerPort: {{ .Values.ports.grpc }}