apiVersion: v1
kind: Service
metadata:
  name: basket-api
spec:
  type: ClusterIP
  ports:
  - name: http-1
    protocol: TCP
    port: {{ .Values.ports.service }}
    targetPort: {{ .Values.ports.container }}
  - name: http-2
    protocol: TCP
    port: {{ .Values.ports.grpc }}
    targetPort: {{ .Values.ports.grpc }}
  selector:
    app: basketapi