apiVersion: apps/v1
kind: Deployment
metadata:
  name: webshoapigw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webshoapigw
  template:
    metadata:
      labels:
        app: webshoapigw
    spec:
      volumes:
      - name: config
        configMap:
          name: webshoapigw-envoy-cm
          items:
          - key: envoy.yaml
            path: envoy.yaml
      containers:
      - name: webshoapigw
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: config
            mountPath: etc/envoy
        ports:
        - containerPort: {{ .Values.ports.container }}
        - containerPort: {{ .Values.ports.admin }}