apiVersion: v1
kind: Service
metadata:
  name: webshopapigw
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.ports.service }}
    targetPort: {{ .Values.ports.container }}
  - name: http2
    protocol: TCP
    port: {{ .Values.ports.admin }}
    targetPort: {{ .Values.ports.admin }}
  selector:
    app: webshopapigw